# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 86aa0dbd44f2634f0e60d3506e94fa8f5e44c6346193a85f32d19fc90698b56eb25d8ea08d9c12bdea70e5f5bde70d253d33c6f857627de85aff01b7233ee758

test:
  secret_key_base: be131da245dc19606c173b662c32508d2e457cdb7a4db7a7e7386d02645f64d43bd85a11ed481297e9236b01f82fae3a0ffb6d293d53af393f91dcbf71e10e01

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
